# Generated by Django 5.1.7 on 2025-05-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db',
            old_name='name',
            new_name='title',
        ),
    ]
