# Generated by Django 5.1.7 on 2025-05-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_db_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
